### ISSUE TITLE
js missing in packaging

### ISSUE THREAD

**Issue by shaib** [pinax/pinax-blog#112]
This is mostly a continuation of #103 -- that issue was closed because the HTML templates are, indeed, in `pinax.templates`. However, `static/js/admin_post_form.js` which was also mentioned there, is not in `pinax.templates`, is included in this git repo, and is missing -- at least by default; we've had to install it manually to prevent errors at the post admin page.

I think it needs to be included.

**Comment by pjmcdermott** [comment]
Confirmed: I have also experienced this

**Comment by grahamu** [comment]
I wonder if the fix is as simple as 

* relocate `admin_post_form.js` to `static/src/js/`, as seen [here](https://github.com/Hamakor/pycon-israel/commit/da1b08685a34aa48cc66732bea903c376115b035)
* update the appconf `ADMIN_JS` location to `"src/js/admin_post_form.js"` [here](https://github.com/pinax/pinax-blog/blob/master/pinax/blog/conf.py#L43)

Then publish a new version, instructing upgrading users to `npm install` or whatever (I'm not sure!) after upgrading. How does that sound @paltman?

**Comment by paltman** [comment]
I've thought about actually removing it and providing instructions on how to add it with a gist of sample js.

**Comment by paltman** [comment]
What I really want to see happen for `pinax-blog` is an authoring interface outside of the Django admin.

**Comment by pjmcdermott** [comment]
Isn't the issue simply that the javascript file is not making it into the pypi package? `django.contrib.staticfiles.finders.AppDirectoriesFinder` provides a perfectly good mechanism to move JS files into a central location.

I don't understand the mechanism, but my `pip` installed version of `pinax-blog` simply doesn't have the `static` folder.

**Comment by paltman** [comment]
Fixed in v7.0.4 (just pushed to PyPI)
